server:
  port: 8000

spring:
  mvc:
    static-path-pattern: /static/**
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://databasepeng.cxkzclvqze2g.ap-northeast-2.rds.amazonaws.com:3306/63building
    username: root
    password: 1q2w3e4r